function createStageUnitConfig(stage, imageList = [], spriteSheetList = []) {
  // 스테이지별 설정이 다르면 조건 분기 가능
  switch (stage) {
    case 1:
      return [
        new UnitType(
          "Kerby",
          imageList[0],
          10,
          32,
          32,
          0.4,
          0,
          50,
          10,
          30,
          5,
          spriteSheetList[0],
          {
            // 유닛 0번 애니메이션
            idle: {
              frameCount: 2,
              frameWidth: 45,
              frameHeight: 35,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 10,
              frameWidth: 60,
              frameHeight: 60,
              startX: 0,
              startY: 64,
              speed: 5,
              scale: 0.3,
              spacing: 0,
            },
            attack: {
              frameCount: 4,
              frameWidth: 60,
              frameHeight: 60,
              startX: 0,
              startY: 336,
              speed: 3,
              scale: 0.3,
              spacing: 0,
            },
          }
        ),
        new UnitType(
          "WaddleDee",
          imageList[1],
          15,
          32,
          32,
          0.4,
          0,
          60,
          12,
          30,
          5,
          spriteSheetList[1],
          {
            // 유닛 1번 애니메이션
            idle: {
              frameCount: 1,
              frameWidth: 133,
              frameHeight: 94,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 10,
              frameWidth: 133,
              frameHeight: 133,
              startX: 0,
              startY: 81,
              speed: 5,
              scale: 1.0,
              spacing: 0,
            },
            attack: {
              frameCount: 4,
              frameWidth: 133,
              frameHeight: 133,
              startX: 9,
              startY: 548,
              speed: 3,
              scale: 1.5, 
            },
          }
        ),
        new UnitType(
          "Zelda",
          imageList[2],
          20,
          32,
          32,
          0.4,
          0,
          70,
          15,
          30,
          5,
          spriteSheetList[2],
          {
            idle: {
              frameCount: 2,
              frameWidth: 60,
              frameHeight: 103,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 3,
              frameWidth: 80,
              frameHeight: 103,
              startX: 0,
              startY: 112,
              speed: 5,
              scale: 0.3,
            },
            attack: {
              frameCount: 2,
              frameWidth: 60,
              frameHeight: 103,
              startX: 0,
              startY: 64,
              speed: 3,
              scale: 1.0,
            },
          }
        ),
        new UnitType(
          "Mario",
          imageList[3],
          30,
          32,
          32,
          0.4,
          0,
          80,
          18,
          30,
          5,
          spriteSheetList[3],
          {
            idle: {
              frameCount: 2,
              frameWidth: 80,
              frameHeight: 105,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 4,
              frameWidth: 80,
              frameHeight: 105,
              startX: 0,
              startY: 105,
              speed: 5,
            },
            attack: {
              frameCount: 2,
              frameWidth: 32,
              frameHeight: 32,
              startX: 0,
              startY: 64,
              speed: 3,
              scale: 1.0,
            },
          }
        ),
        new UnitType(
          "Boo",
          imageList[4],
          50,
          32,
          32,
          0.4,
          0,
          100,
          25,
          30,
          5,
          spriteSheetList[4],
          {
            idle: {
              frameCount: 2,
              frameWidth: 70,
              frameHeight: 75,
              startX: 110,
              startY: 140,
              speed: 10,
              scale: 1.0,
              spacing: 30,
            },
            walk: {
              frameCount: 3,
              frameWidth: 70,
              frameHeight: 75,
              startX: 730,
              startY: 140,
              speed: 5,
              scale: 1.0,
              spacing: 30,
            },
            attack: {
              frameCount: 2,
              frameWidth: 32,
              frameHeight: 32,
              startX: 0,
              startY: 64,
              speed: 3,
              scale: 1.0,
            },
          }
        ),
      ];

    default:
      return []; // 없는 스테이지는 빈 배열
  }
}
