function createStageUnitConfig(stage, imageList = [], spriteSheetList = []) {
  // 스테이지별 설정이 다르면 조건 분기 가능
  switch (stage) {
    case 1:
      return [
        new UnitType(
          "Kerby",
          imageList[0],
          10,
          40,
          32,
          0.4,
          0,
          50,
          10,
          30,
          5,
          spriteSheetList[0],
          {
            // 유닛 0번 애니메이션
            idle: {
              frameCount: 2,
              frameWidth: 60,
              frameHeight: 48,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 10,
              frameWidth: 60,
              frameHeight: 48,
              startX: 0,
              startY: 78,
              speed: 5,
              scale: 0.3,
              spacing: 0,
            },
            attack: {
              frameCount: 4,
              frameWidth: 60,
              frameHeight: 48,
              startX: 0,
              startY: 350,
              speed: 3,
              scale: 0.3,
              spacing: 0,
            },
          }
        ),
        new UnitType(
          "WaddleDee",
          imageList[1],
          15,
          40,
          32,
          0.4,
          0,
          60,
          12,
          30,
          5,
          spriteSheetList[1],
          {
            // 유닛 1번 애니메이션
            idle: {
              frameCount: 1,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 10,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 111,
              speed: 5,
              scale: 1.0,
              spacing: 0,
            },
            attack: {
              frameCount: 4,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 574,
              speed: 3,
              scale: 1.0,
            },
          }
        ),
        new UnitType(
          "Zelda",
          imageList[2],
          20,
          40,
          32,
          0.4,
          0,
          70,
          15,
          30,
          5,
          spriteSheetList[2],
          {
            idle: {
              frameCount: 2,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 7,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 107,
              speed: 5,
              scale: 0.3,
            },
            attack: {
              frameCount: 3,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 435,
              speed: 5,
              scale: 1.0,
            },
          }
        ),
        new UnitType(
          "Mario",
          imageList[3],
          30,
          40,
          32,
          0.4,
          0,
          80,
          18,
          30,
          5,
          spriteSheetList[3],
          {
            idle: {
              frameCount: 2,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 7,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 103,
              speed: 5,
            },
            attack: {
              frameCount: 4,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 434,
              speed: 5,
              scale: 1.0,
            },
          }
        ),
        new UnitType(
          "Boo",
          imageList[4],
          50,
          40,
          32,
          0.4,
          0,
          100,
          25,
          30,
          5,
          spriteSheetList[4],
          {
            idle: {
              frameCount: 2,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 0,
              speed: 10,
              scale: 1.0,
            },
            walk: {
              frameCount: 2,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 106,
              speed: 10,
              scale: 1.0,
            },
            attack: {
              frameCount: 4,
              frameWidth: 132,
              frameHeight: 106,
              startX: 0,
              startY: 360,
              speed: 2,
              scale: 1.0,

            },
          }
        ),
      ];

    default:
      return []; // 없는 스테이지는 빈 배열
  }
}
